### PR TITLE
Styling changes for urban dashboard

### PR DESCRIPTION
**Pull request by anisbhsl**
- [x] Fix the font size issues
- [x] Change colors for pie-charts 
- [x] Shift the map to the right to increase the viewport for focused region
- [x] Fixed spacing issue

VULCAN Interface: http://ghgc-custom-interfaces-develop-urban-dashboard.s3-website-us-west-2.amazonaws.com/?dataset=vulcan

GRA2PES Interface: http://ghgc-custom-interfaces-develop-urban-dashboard.s3-website-us-west-2.amazonaws.com/?dataset=gra2pes

### CODE REVIEW

**Comment by anisbhsl** [comment]
Todo: 

update the vulcan and gra2pes link: 

https://deploy-preview-484--ghg-demo.netlify.app/data-catalog/vulcan-ffco2-yeargrid-v4
https://deploy-preview-484--ghg-demo.netlify.app/data-catalog/gra2pes-ghg-monthgrid-v1

**Comment by sanzog03** [comment]
Bug: Around the marker edges where the tooltip appears if we bring the mouse hover event, the tooltip flickers.

**Comment by anisbhsl** [comment]
Latest build deployed to s3 links mentioned in the description above.

**Review by slesaad — APPROVED** [review]

**Comment by anisbhsl** [comment]
Waiting on the y-axis label confirmation for vulcan sectoral plot. This PR will be updated and merged after it is confirmed/updated.

**Pull request merged**
