### PR TITLE
updated global gitignore to not ignore data dir

### PR DESCRIPTION
**Pull request by sanzog03**
updated global readme

### CODE REVIEW

**Review by amarouane-ABDELHAK — CHANGES_REQUESTED** [review]
We don't want to commit the data folder across all custom interfaces, as this would significantly increase the repository size. Instead, you can explicitly add the data folder only where it's necessary.

**Comment by sanzog03** [comment]
> We don't want to commit the data folder across all custom interfaces, as this would significantly increase the repository size. Instead, you can explicitly add the data folder only where it's necessary.

I have added data dir to the gitignore to ignore the data in the emit directory. And for now, in the goes interface, I have renamed the metadata directory to be dataset instead of data.

**Comment by amarouane-ABDELHAK** [comment]
Can you look at this error before merging https://github.com/US-GHG-Center/custom-interfaces/actions/runs/11804564917/job/32885054555?pr=142#step:7:157

**Comment by sanzog03** [comment]
> Can you look at this error before merging https://github.com/US-GHG-Center/custom-interfaces/actions/runs/11804564917/job/32885054555?pr=142#step:7:157

This should not have been caused by the change. Re-bulding to see if the error resolves. 🤞

**Comment by sanzog03** [comment]
still very weird on why this build is failing.
created a new pr with the only needed change.
https://github.com/US-GHG-Center/custom-interfaces/pull/144

**Pull request closed without merging**
