### PR TITLE
Add the capability to search by plume id

### PR DESCRIPTION
**Pull request by amarouane-ABDELHAK**
Add the capability to search by plume id

### CODE REVIEW

**Comment by slesaad** [comment]
@amarouane-ABDELHAK can you add a screenshot? we need netlify previews 👀

**Comment by amarouane-ABDELHAK** [comment]
image
image

**Comment by amarouane-ABDELHAK** [comment]
> @amarouane-ABDELHAK can you add a screenshot? we need netlify previews 👀

I think all netlify previews points to EMIT prod

**Comment by slesaad** [comment]
> > @amarouane-ABDELHAK can you add a screenshot? we need netlify previews 👀
> 
> I think all netlify previews points to EMIT prod

I meant we should set up netlify previews for this repository too

**Review by slesaad — APPROVED** [review]

**Pull request merged**
